Disabled isolatedModules & noImplicitAny flags.
isolatedModules flag was causing vuejs reactivity compilation errors.
See error below and https://github.com/vitejs/vite/issues/5814 & https://github.com/vuejs/core/issues/1228

```
node_modules/@vue/reactivity/dist/reactivity.d.ts:26:15 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

26     readonly [ReactiveFlags.IS_READONLY]: boolean;
```

noImplicitAny flag was causing compilation errors when using named slots.